In [1]:
import polars as pl

In [8]:
data = pl.read_parquet("s:/campaignfinance/data/FEC/API/contributions/super_contributions.parquet")

In [89]:
data.filter((pl.col(name="entity_type")=="IND")).shape

(1927183, 29)

In [90]:
CONTRIBUTIONS_FILE_PATH = "S:/campaignfinance/data/FEC/API/contributions/"

In [91]:
individual_contributions = data.filter(pl.col("entity_type")=="IND")
organization_contributions = data.filter(pl.col("entity_type")!="IND")
undefined_contributions = data.filter(pl.col("entity_type").is_null())
individual_contributions.write_parquet(f"{CONTRIBUTIONS_FILE_PATH}super_individual_contributions.parquet")
organization_contributions.write_parquet(f"{CONTRIBUTIONS_FILE_PATH}super_organization_contributions.parquet")
undefined_contributions.write_csv(f"{CONTRIBUTIONS_FILE_PATH}super_undefined_contributions.csv")

KeyboardInterrupt:

In [99]:
organization_contributions

shape: (793_213, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ committee ┆ amendment ┆ amendment ┆ contribut ┆ … ┆ receipt_t ┆ receipt_t ┆ image_num ┆ pdf_url  │
│ _id       ┆ _indicato ┆ _indicato ┆ ion_recei ┆   ┆ ype_desc  ┆ ype_full  ┆ ber       ┆ ---      │
│ ---       ┆ r         ┆ r_desc    ┆ pt_amount ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆          │
│           ┆ str       ┆ str       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ C00877886 ┆ A         ┆ ADD       ┆ 250.0     ┆ … ┆ null      ┆ TOTAL     ┆ 202602049 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆           ┆ EARMARKED ┆ 825918351 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆           ┆ THRUGH    ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆           ┆ ACTBLUE…  ┆           ┆ /cgi-b…  │
│ C00877886 ┆ A         ┆ ADD       ┆ 1000.0    ┆ … ┆ null      ┆ TOTAL     ┆ 202602049 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆           ┆ EARMARKED ┆ 825918351 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆           ┆ THGOUGH   ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆           ┆ ACTBLU…   ┆           ┆ /cgi-b…  │
│ C00877886 ┆ A         ┆ ADD       ┆ 250.0     ┆ … ┆ null      ┆ TOTAL     ┆ 202602049 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆           ┆ EARMARKED ┆ 825918350 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆           ┆ THROUGH   ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆           ┆ ACTBLU…   ┆           ┆ /cgi-b…  │
│ C00877886 ┆ A         ┆ ADD       ┆ 500.0     ┆ … ┆ null      ┆ TOTAL     ┆ 202507169 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆           ┆ EARMARKED ┆ 763553748 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆           ┆ THROUGH   ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆           ┆ CONDUI…   ┆           ┆ /cgi-b…  │
│ C00877886 ┆ A         ┆ ADD       ┆ 15000.0   ┆ … ┆ NON-FEDER ┆ CONTRIBUT ┆ 202507169 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆ AL        ┆ ION       ┆ 763553749 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆ RECEIPT   ┆           ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆ FROM      ┆           ┆           ┆ /cgi-b…  │
│           ┆           ┆           ┆           ┆   ┆ PERSO…    ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ C00467258 ┆ A         ┆ ADD       ┆ 50.0      ┆ … ┆ null      ┆ null      ┆ 109302276 ┆ http://d │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 98        ┆ ocquery. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ fec.gov/ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cgi-bi…  │
│ C00467258 ┆ A         ┆ ADD       ┆ 100.0     ┆ … ┆ null      ┆ null      ┆ 109302276 ┆ http://d │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 98        ┆ ocquery. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ fec.gov/ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cgi-bi…  │
│ C00467258 ┆ A         ┆ ADD       ┆ 500.0     ┆ … ┆ CONTRIBUT ┆ null      ┆ 109302276 ┆ http://d │
│           ┆           ┆           ┆           ┆   ┆ ION       ┆           ┆ 97        ┆ ocquery. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ fec.gov/ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cgi-bi…  │
│ C00677120 ┆ A         ┆ ADD       ┆ 10000.0   ┆ … ┆ null      ┆ null      ┆ 201810039 ┆ http://d │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 124283998 ┆ ocquery. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ fec.gov/ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cgi-bi…  │
│ C00677120 ┆ A         ┆ ADD       ┆ 50000.0   ┆ … ┆ null      ┆ null      ┆ 201810039 ┆ http://d │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 124283999 ┆ ocquery. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ fec.gov/ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cgi-bi…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [105]:
organization_contributions[["contributor_name", "contributor_city", "contributor_state", "entity_type", "contributor_id"]].drop_nulls(subset=["contributor_name"]).unique()

shape: (21_724, 5)
┌────────────────────────────┬──────────────────┬───────────────────┬─────────────┬────────────────┐
│ contributor_name           ┆ contributor_city ┆ contributor_state ┆ entity_type ┆ contributor_id │
│ ---                        ┆ ---              ┆ ---               ┆ ---         ┆ ---            │
│ str                        ┆ str              ┆ str               ┆ str         ┆ str            │
╞════════════════════════════╪══════════════════╪═══════════════════╪═════════════╪════════════════╡
│ USA PAC - UNITED FOR A     ┆ LOS ANGELES      ┆ CA                ┆ PAC         ┆ C00422774      │
│ STRONG …                   ┆                  ┆                   ┆             ┆                │
│ FERRAIOLI, WIELKOTZ,       ┆ POMPTON LAKES    ┆ NJ                ┆ ORG         ┆ null           │
│ CERRULO                    ┆                  ┆                   ┆             ┆                │
│ DEL RAY MEDIA              ┆ ALEXANDRIA       ┆ VA                ┆ ORG         ┆ null           │
│ JASON BACON FOR CONGRESS   ┆ TUCSON           ┆ AZ                ┆ CCM         ┆ C00734715      │
│ HEALTH CARE INFORMATION    ┆ OMAHA            ┆ NE                ┆ ORG         ┆ null           │
│ SYSTEM…                    ┆                  ┆                   ┆             ┆                │
│ …                          ┆ …                ┆ …                 ┆ …           ┆ …              │
│ BASIS EDUCATIONAL VENTURES ┆ SCOTTSDALE       ┆ AZ                ┆ ORG         ┆ null           │
│ LLC                        ┆                  ┆                   ┆             ┆                │
│ NOLAN H. BRUNSON INC.      ┆ HOBBS            ┆ NM                ┆ ORG         ┆ null           │
│ PHOENIX FIRE FIGHTERS      ┆ PHOENIX          ┆ AZ                ┆ ORG         ┆ null           │
│ LOCAL 49…                  ┆                  ┆                   ┆             ┆                │
│ DEMOCRATIC GOVERNORS'      ┆ WASHINGTON       ┆ DC                ┆ ORG         ┆ null           │
│ ASSOCIAT…                  ┆                  ┆                   ┆             ┆                │
│ ZIBEN-MARE                 ┆ BLOOMFIELD       ┆ MI                ┆ ORG         ┆ null           │
└────────────────────────────┴──────────────────┴───────────────────┴─────────────┴────────────────┘

In [33]:
data.filter((pl.col("contributor_id").is_not_null()) & (pl.col("entity_type") == "IND"))["contributor_id"].unique()

shape: (32,)
Series: 'contributor_id' [str]
[
	"C00581397"
	"C00714725"
	"C00571703"
	"C00122101"
	"C00517173"
	…
	"00625749"
	"C00000935"
	" "
	"C 0.0.58"
	"C00401224"
]

In [13]:
data["entity_type"].unique()

shape: (8,)
Series: 'entity_type' [str]
[
	"IND"
	"COM"
	"CCM"
	"PTY"
	null
	"PAC"
	"ORG"
	"CAN"
]

In [2]:
DATA_PATH = "s:/campaignfinance/data/"
cand_data = pl.read_parquet("C:/Users/zih028/Dropbox/Campaign Contributions/input/contributions/firms_leadership_pacs_contributions.parquet")
cand_data

shape: (59_832, 67)
┌───────────┬────────────┬────────────┬───────────┬───┬────────────┬───────┬───────────┬───────────┐
│ cmte_id   ┆ transactio ┆ election_i ┆ amendment ┆ … ┆ NAICS_Nati ┆ index ┆ cand_id   ┆ cmte_type │
│ ---       ┆ n_type     ┆ ndicator   ┆ ---       ┆   ┆ onal_Indus ┆ ---   ┆ ---       ┆ ---       │
│ str       ┆ ---        ┆ ---        ┆ str       ┆   ┆ try        ┆ f64   ┆ str       ┆ str       │
│           ┆ str        ┆ str        ┆           ┆   ┆ ---        ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ str        ┆       ┆           ┆           │
╞═══════════╪════════════╪════════════╪═══════════╪═══╪════════════╪═══════╪═══════════╪═══════════╡
│ C00363879 ┆ 24K        ┆ null       ┆ A         ┆ … ┆ ['Fossil   ┆ null  ┆ H6MO07128 ┆ D         │
│           ┆            ┆            ┆           ┆   ┆ Fuel       ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Electric   ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Power G…   ┆       ┆           ┆           │
│ C00363879 ┆ 24K        ┆ null       ┆ A         ┆ … ┆ ['Fossil   ┆ null  ┆ H2MD05155 ┆ D         │
│           ┆            ┆            ┆           ┆   ┆ Fuel       ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Electric   ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Power G…   ┆       ┆           ┆           │
│ C00363879 ┆ 24K        ┆ null       ┆ A         ┆ … ┆ ['Fossil   ┆ null  ┆ H4MS01078 ┆ D         │
│           ┆            ┆            ┆           ┆   ┆ Fuel       ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Electric   ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Power G…   ┆       ┆           ┆           │
│ C00363879 ┆ 24K        ┆ null       ┆ A         ┆ … ┆ ['Fossil   ┆ null  ┆ H4TX06117 ┆ D         │
│           ┆            ┆            ┆           ┆   ┆ Fuel       ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Electric   ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Power G…   ┆       ┆           ┆           │
│ C00363879 ┆ 24K        ┆ null       ┆ A         ┆ … ┆ ['Fossil   ┆ null  ┆ H4LA07029 ┆ D         │
│           ┆            ┆            ┆           ┆   ┆ Fuel       ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Electric   ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Power G…   ┆       ┆           ┆           │
│ …         ┆ …          ┆ …          ┆ …         ┆ … ┆ …          ┆ …     ┆ …         ┆ …         │
│ C00312785 ┆ 24Z        ┆ P2024      ┆ N         ┆ … ┆ ['Extermin ┆ null  ┆ H0MI02094 ┆ D         │
│           ┆            ┆            ┆           ┆   ┆ ating and  ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Pest       ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Contr…     ┆       ┆           ┆           │
│ C00312785 ┆ 24Z        ┆ P2024      ┆ N         ┆ … ┆ ['Extermin ┆ null  ┆ H8PA10147 ┆ D         │
│           ┆            ┆            ┆           ┆   ┆ ating and  ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Pest       ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Contr…     ┆       ┆           ┆           │
│ C00312785 ┆ 24Z        ┆ P2024      ┆ N         ┆ … ┆ ['Extermin ┆ null  ┆ H8PA10147 ┆ D         │
│           ┆            ┆            ┆           ┆   ┆ ating and  ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Pest       ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Contr…     ┆       ┆           ┆           │
│ C00312785 ┆ 24Z        ┆ P2024      ┆ N         ┆ … ┆ ['Extermin ┆ null  ┆ H2NC08185 ┆ D         │
│           ┆            ┆            ┆           ┆   ┆ ating and  ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Pest       ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Contr…     ┆       ┆           ┆           │
│ C00034470 ┆ 24Z        ┆ P2024      ┆ N         ┆ … ┆ ['Wine and ┆ null  ┆ H2KY03206 ┆ D         │
│           ┆            ┆            ┆           ┆   ┆ Distilled  ┆       ┆           ┆           │
│           ┆            ┆            ┆           ┆   ┆ Alcoholic… ┆       ┆           ┆           │
└───────────┴────────────┴────────────┴───────────┴───┴────────────┴───────┴───────────┴───────────┘

In [ ]:
cand_data

KeyboardInterrupt

In [3]:
DATA_PATH = "s:/campaignfinance/data/"
contributions = pl.read_parquet(f"{DATA_PATH}FEC/processed/firms_principal_committees_contributions.parquet")

In [4]:
firm_size = (
    contributions
    .filter(pl.col("amount") > 0)
    .group_by(["cmte_id", "cycle"])
    .agg([
        pl.col("amount").sum().alias("firm_amount"),
        pl.col("cand_id").n_unique().alias("firm_candidates")
    ])
)

In [9]:
firm_size.filter((pl.col("cmte_id") == "C00142489") & (pl.col("cycle") >= 2010))

shape: (5, 4)
┌───────────┬───────┬─────────────┬─────────────────┐
│ cmte_id   ┆ cycle ┆ firm_amount ┆ firm_candidates │
│ ---       ┆ ---   ┆ ---         ┆ ---             │
│ str       ┆ i64   ┆ f64         ┆ u32             │
╞═══════════╪═══════╪═════════════╪═════════════════╡
│ C00142489 ┆ 2018  ┆ 38000.0     ┆ 27              │
│ C00142489 ┆ 2016  ┆ 39500.0     ┆ 25              │
│ C00142489 ┆ 2020  ┆ 14500.0     ┆ 8               │
│ C00142489 ┆ 2012  ┆ 33000.0     ┆ 25              │
│ C00142489 ┆ 2010  ┆ 36500.0     ┆ 27              │
└───────────┴───────┴─────────────┴─────────────────┘

In [10]:
contributions= (
    contributions
    .filter(pl.col("cand_id").str.starts_with("H"))
    #.filter(pl.col("amount") > 0)
    .select([
        "cmte_id", "name", "amount", "cand_id", "rcpt_cmte", "year", "month", "day", "cycle",
        "cmte_nm", "connected_org_nm", "corporation", "ttl_receipts", "instrument", "cusip",
        "hq", "hq_state", "hq_city", "ric", "permid", "GICS_Sector", "GICS_Industry_Group",
        "GICS_Industry", "GIS_Subindustry", "TRBC_Econ_Sector", "TRBC_Business_Sector",
        "TRBC_Industry_Group", "TRBC_Industry", "TRBC_ID", "NAICS_Sector", "NAICS_Subsector",
        "NAICS_Industry_Group"
    ])
    .join(firm_size, on = ["cmte_id", "cycle"], how = "left")
)

In [11]:
contributions.filter(pl.col("cmte_id") == "C00142489")

shape: (181, 34)
┌───────────┬────────────┬────────┬───────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ cmte_id   ┆ name       ┆ amount ┆ cand_id   ┆ … ┆ NAICS_Subs ┆ NAICS_Ind ┆ firm_amou ┆ firm_cand │
│ ---       ┆ ---        ┆ ---    ┆ ---       ┆   ┆ ector      ┆ ustry_Gro ┆ nt        ┆ idates    │
│ str       ┆ str        ┆ f64    ┆ str       ┆   ┆ ---        ┆ up        ┆ ---       ┆ ---       │
│           ┆            ┆        ┆           ┆   ┆ str        ┆ ---       ┆ f64       ┆ u32       │
│           ┆            ┆        ┆           ┆   ┆            ┆ str       ┆           ┆           │
╞═══════════╪════════════╪════════╪═══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ C00142489 ┆ null       ┆ 500.0  ┆ H2VA09010 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 25000.0   ┆ 23        │
│           ┆            ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ ties',     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ 'Ut…       ┆ n, T…     ┆           ┆           │
│ C00142489 ┆ null       ┆ 1000.0 ┆ H2ND00057 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 25000.0   ┆ 23        │
│           ┆            ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ ties',     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ 'Ut…       ┆ n, T…     ┆           ┆           │
│ C00142489 ┆ null       ┆ 500.0  ┆ H8WI01024 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 25000.0   ┆ 23        │
│           ┆            ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ ties',     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ 'Ut…       ┆ n, T…     ┆           ┆           │
│ C00142489 ┆ null       ┆ 1000.0 ┆ H6MN08047 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 25000.0   ┆ 23        │
│           ┆            ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ ties',     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ 'Ut…       ┆ n, T…     ┆           ┆           │
│ C00142489 ┆ null       ┆ 1000.0 ┆ H0MN00013 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 25000.0   ┆ 23        │
│           ┆            ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ ties',     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ 'Ut…       ┆ n, T…     ┆           ┆           │
│ …         ┆ …          ┆ …      ┆ …         ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ C00142489 ┆ EMMER,     ┆ 1000.0 ┆ H4MN06087 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 14500.0   ┆ 8         │
│           ┆ THOMAS     ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆ EARL JR.   ┆        ┆           ┆   ┆ ties',     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ 'Ut…       ┆ n, T…     ┆           ┆           │
│ C00142489 ┆ STAUBER,   ┆ 2500.0 ┆ H8MN08043 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 14500.0   ┆ 8         │
│           ┆ PETER      ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆ ALLEN      ┆        ┆           ┆   ┆ ties',     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ 'Ut…       ┆ n, T…     ┆           ┆           │
│ C00142489 ┆ FRED       ┆ 2000.0 ┆ H0PA12181 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 14500.0   ┆ 8         │
│           ┆ KELLER FOR ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆ CONGRESS,  ┆        ┆           ┆   ┆ ties',     ┆ Generatio ┆           ┆           │
│           ┆ .          ┆        ┆           ┆   ┆ 'Ut…       ┆ n, T…     ┆           ┆           │
│ C00142489 ┆ LUCAS FOR  ┆ 1000.0 ┆ H4OK06056 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 14500.0   ┆ 8         │
│           ┆ CONGRESS,  ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆ .          ┆        ┆           ┆   ┆ ties',     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ 'Ut…       ┆ n, T…     ┆           ┆           │
│ C00142489 ┆ MULLIN FOR ┆ 2000.0 ┆ H2OK02083 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 14500.0   ┆ 8         │
│           ┆ CONGRESS,  ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆ .          ┆        ┆           ┆   ┆ ties',     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ 'Ut…       ┆ n, T…     ┆           ┆           │
└───────────┴────────────┴────────┴───────────┴───┴────────────┴───────────┴───────────┴───────────┘