In [1]:
import polars as pl
DATA_PATH = "S:/campaignfinance/data/"
type = "super"

In [2]:
contributions = pl.read_parquet(f"{DATA_PATH}FEC/API/contributions/{type}_contributions.parquet")

In [52]:
individual_contributions = contributions.filter(pl.col("entity_type")=="IND")
organization_contributions = contributions.filter(pl.col("entity_type")!="IND")
undefined_contributions = contributions.filter(pl.col("entity_type").is_null())
organizations = (
            organization_contributions
            .group_by(["contributor_name", "contributor_city", "contributor_state", "entity_type", "contributor_id"])
            .agg(pl.col("contribution_receipt_amount").sum())
        )

In [53]:
organizations.sort("contribution_receipt_amount", descending = True)

shape: (21_724, 6)
┌────────────────┬────────────────┬────────────────┬─────────────┬────────────────┬────────────────┐
│ contributor_na ┆ contributor_ci ┆ contributor_st ┆ entity_type ┆ contributor_id ┆ contribution_r │
│ me             ┆ ty             ┆ ate            ┆ ---         ┆ ---            ┆ eceipt_amount  │
│ ---            ┆ ---            ┆ ---            ┆ str         ┆ str            ┆ ---            │
│ str            ┆ str            ┆ str            ┆             ┆                ┆ f64            │
╞════════════════╪════════════════╪════════════════╪═════════════╪════════════════╪════════════════╡
│ ACTBLUE        ┆ SOMERVILLE     ┆ MA             ┆ PAC         ┆ C00401224      ┆ 4.3215e8       │
│ SMP            ┆ WASHINGTON     ┆ DC             ┆ ORG         ┆ C00484642      ┆ 3.2373e8       │
│ MAJORITY       ┆ WASHINGTON     ┆ DC             ┆ ORG         ┆ null           ┆ 2.7416e8       │
│ FORWARD        ┆                ┆                ┆             ┆                ┆                │
│ COINBASE       ┆ OAKLAND        ┆ CA             ┆ ORG         ┆ null           ┆ 2.3559247e8    │
│ ONE NATION     ┆ HAYMARKET      ┆ VA             ┆ ORG         ┆ null           ┆ 1.9629e8       │
│ …              ┆ …              ┆ …              ┆ …           ┆ …              ┆ …              │
│ WIN JUSTICE    ┆ WASHINGTON     ┆ DC             ┆ ORG         ┆ null           ┆ -480000.0      │
│ (FLORIDA       ┆                ┆                ┆             ┆                ┆                │
│ COMMITTEE…     ┆                ┆                ┆             ┆                ┆                │
│ BLACKSTORM LLC ┆ LAS VEGAS      ┆ NV             ┆ ORG         ┆ null           ┆ -500000.0      │
│ FLORIDA        ┆ BEVERLY        ┆ MA             ┆ PAC         ┆ C00881474      ┆ -1.2215e6      │
│ PATRIOTS PAC   ┆                ┆                ┆             ┆                ┆                │
│ SPDR FUNDS     ┆ NEW YORK       ┆ NY             ┆ ORG         ┆ null           ┆ -5.1342e6      │
│ ISHARES BY     ┆ SAN FRANCISCO  ┆ CA             ┆ ORG         ┆ null           ┆ -1.4028e7      │
│ BLACKROCK      ┆                ┆                ┆             ┆                ┆                │
└────────────────┴────────────────┴────────────────┴─────────────┴────────────────┴────────────────┘

In [49]:
line_nums = ["11A1", "11B", "11C", "11D", "12", "13", "13A", "13B", "17A", "17C", "17D"]

In [51]:
contributions.shape

(2723716, 29)

In [62]:
contributions.filter(pl.col("contributor_name") == "CHEVRON CORPORATION")

shape: (22, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ committee ┆ amendment ┆ amendment ┆ contribut ┆ … ┆ receipt_t ┆ receipt_t ┆ image_num ┆ pdf_url  │
│ _id       ┆ _indicato ┆ _indicato ┆ ion_recei ┆   ┆ ype_desc  ┆ ype_full  ┆ ber       ┆ ---      │
│ ---       ┆ r         ┆ r_desc    ┆ pt_amount ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆          │
│           ┆ str       ┆ str       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ C00571703 ┆ N         ┆ NO CHANGE ┆ 750000.0  ┆ … ┆ NON-FEDER ┆ CONTRIBUT ┆ 202602269 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆ AL        ┆ ION       ┆ 837863599 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆ RECEIPT   ┆           ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆ FROM      ┆           ┆           ┆ /cgi-b…  │
│           ┆           ┆           ┆           ┆   ┆ PERSO…    ┆           ┆           ┆          │
│ C00571703 ┆ N         ┆ NO CHANGE ┆ 750000.0  ┆ … ┆ NON-FEDER ┆ CONTRIBUT ┆ 202511049 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆ AL        ┆ ION       ┆ 792571870 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆ RECEIPT   ┆           ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆ FROM      ┆           ┆           ┆ /cgi-b…  │
│           ┆           ┆           ┆           ┆   ┆ PERSO…    ┆           ┆           ┆          │
│ C00571703 ┆ A         ┆ ADD       ┆ 1e6       ┆ … ┆ NON-FEDER ┆ CONTRIBUT ┆ 202410159 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆ AL        ┆ ION       ┆ 687740153 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆ RECEIPT   ┆           ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆ FROM      ┆           ┆           ┆ /cgi-b…  │
│           ┆           ┆           ┆           ┆   ┆ PERSO…    ┆           ┆           ┆          │
│ C00571703 ┆ A         ┆ ADD       ┆ 1e6       ┆ … ┆ NON-FEDER ┆ CONTRIBUT ┆ 202407159 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆ AL        ┆ ION       ┆ 659819710 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆ RECEIPT   ┆           ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆ FROM      ┆           ┆           ┆ /cgi-b…  │
│           ┆           ┆           ┆           ┆   ┆ PERSO…    ┆           ┆           ┆          │
│ C00571703 ┆ N         ┆ NO CHANGE ┆ 1e6       ┆ … ┆ NON-FEDER ┆ CONTRIBUT ┆ 202407159 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆ AL        ┆ ION       ┆ 659839425 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆ RECEIPT   ┆           ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆ FROM      ┆           ┆           ┆ /cgi-b…  │
│           ┆           ┆           ┆           ┆   ┆ PERSO…    ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ C00571703 ┆ N         ┆ NO CHANGE ┆ 500000.0  ┆ … ┆ NON-FEDER ┆ CONTRIBUT ┆ 202002069 ┆ http://d │
│           ┆           ┆           ┆           ┆   ┆ AL        ┆ ION       ┆ 186471314 ┆ ocquery. │
│           ┆           ┆           ┆           ┆   ┆ RECEIPT   ┆           ┆           ┆ fec.gov/ │
│           ┆           ┆           ┆           ┆   ┆ FROM      ┆           ┆           ┆ cgi-bi…  │
│           ┆           ┆           ┆           ┆   ┆ PERSO…    ┆           ┆           ┆          │
│ C00737411 ┆ A         ┆ ADD       ┆ 50000.0   ┆ … ┆ NON-FEDER ┆ null      ┆ 202507119 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆ AL        ┆           ┆ 762757932 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆ RECEIPT   ┆           ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆ FROM      ┆           ┆           ┆ /cgi-b…  │
│           ┆           ┆           ┆           ┆   ┆ PERSO…    ┆           ┆           ┆          │
│ C00737411 ┆ A         ┆ ADD       ┆ 50000.0   ┆ … ┆ NON-FEDER ┆ null      ┆ 202407099 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆ AL        ┆           ┆ 652735893 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆ RECEIPT   ┆           ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆ FROM      ┆           ┆           ┆ /cgi-b…  │
│           ┆           ┆           ┆           ┆   ┆ PERSO…    ┆           ┆           ┆          │
│ C00737411 ┆ A         ┆ ADD       ┆ 50000.0   ┆ … ┆ NON-FEDER ┆ null      ┆ 202401169 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆ AL        ┆           ┆ 600090314 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆ RECEIPT   ┆           ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆ FROM      ┆           ┆           ┆ /cgi-b…  │
│           ┆           ┆           ┆           ┆   ┆ PERSO…    ┆           ┆           ┆          │
│ C00737411 ┆ A         ┆ ADD       ┆ 50000.0   ┆ … ┆ NON-FEDER ┆ null      ┆ 202207099 ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆ AL        ┆           ┆ 518295402 ┆ docquery │
│           ┆           ┆           ┆           ┆   ┆ RECEIPT   ┆           ┆           ┆ .fec.gov │
│           ┆           ┆           ┆           ┆   ┆ FROM      ┆           ┆           ┆ /cgi-b…  │
│           ┆           ┆           ┆           ┆   ┆ PERSO…    ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [43]:
contributions = contributions.with_columns(
    pl.col("line_number").str.replace_all("11AI", "11A1")
)

In [58]:
committee_contributions = contributions.filter(pl.col("line_number").is_in(["11C", "17C"]))

In [59]:
committee_contributions.shape

(15098, 29)

In [72]:
import os
import json 
import pandas as pd

CONFIG_PATH = "S:/campaignfinance/config"
os.environ["LD_LIB_CONFIG_PATH"] = CONFIG_PATH
DATA_PATH = "S:/campaignfinance/data/LSEG/"

import lseg.data as ld
ld.open_session()

In [68]:
LSEG_PATH = "S:/campaignfinance/scripts/LSEG/"
def collapse(x):
    x = [v for v in x if pd.notnull(v) and v != '']
    return x if x else None
COLLAPSE_COLS = ["TRBC_ID", "TRBC_Econ_Sector", "TRBC_Business_Sector", "TRBC_Industry_Group",
                 "TRBC_Industry", "TRBC_Activity", "NAICS_ID", "NAICS_Sector", "NAICS_Subsector",
                 "NAICS_Industry_Group", "NAICS_International_Industry", "NAICS_National_Industry"]



with open(f"{LSEG_PATH}data_fields.json", "r") as f:
    data_fields = json.load(f)
    fields = list(data_fields.keys())
    col_names = list(data_fields.values())

agg_dict = {
    col: collapse if col in COLLAPSE_COLS else "first" 
    for col in col_names
}

In [69]:
df = ld.get_data(universe = "COIN.O", fields = fields)

s:\campaignfinance\.venv\Lib\site-packages\lseg\data\_tools\_dataframe.py:192:FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [70]:
df.columns = ["instrument"] + col_names

In [73]:
df.groupby("instrument", as_index=False).agg(agg_dict).reset_index().to_csv(f"{DATA_PATH}Addon_firms.csv", index=False)

In [1]:
import polars as pl
DATA_PATH = "s:/campaignfinance/data/"

In [4]:
contributions = pl.read_parquet(f"{DATA_PATH}house_firm_contributions.parquet")

In [2]:
cand_data1 = pl.read_parquet(f"{DATA_PATH}house_firm_cand_election_year.parquet")
cand_data2 = pl.read_parquet(f"{DATA_PATH}house_firm_cand.parquet")

In [3]:
cand_data2.filter(pl.col("total_amount") < 0)

shape: (0, 46)
┌─────────┬───────┬─────────────┬──────────────┬───┬────────┬────────────┬──────┬──────────────┐
│ cmte_id ┆ cycle ┆ corporation ┆ ttl_receipts ┆ … ┆ nparty ┆ contribute ┆ year ┆ prior_amount │
│ ---     ┆ ---   ┆ ---         ┆ ---          ┆   ┆ ---    ┆ ---        ┆ ---  ┆ ---          │
│ str     ┆ i64   ┆ str         ┆ f64          ┆   ┆ u32    ┆ i32        ┆ i64  ┆ i32          │
╞═════════╪═══════╪═════════════╪══════════════╪═══╪════════╪════════════╪══════╪══════════════╡
└─────────┴───────┴─────────────┴──────────────┴───┴────────┴────────────┴──────┴──────────────┘

In [10]:
cand_data1.filter(pl.col("contribute") == 1)["uncertainty"].median()

4.0

In [11]:
cand_data2.filter(pl.col("contribute") == 1)["uncertainty"].median()

4.0

In [19]:
contributions.filter(
            (pl.col("year") % 2 == 0) & (pl.col("month") < 11)
        )["certainty"].mean()

ColumnNotFoundError: "certainty" not found

In [18]:
contributions.filter(
            (pl.col("year") % 2 == 1)
        )["cmte_id"].unique().count()

1923

In [12]:
contributions = contributions.filter(
    (pl.col("year") >= 2009)  & (pl.col("year") <= 2022)
)

In [20]:
contributions

shape: (567_263, 34)
┌───────────┬────────────┬────────┬───────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ cmte_id   ┆ name       ┆ amount ┆ cand_id   ┆ … ┆ NAICS_Subs ┆ NAICS_Ind ┆ firm_amou ┆ firm_cand │
│ ---       ┆ ---        ┆ ---    ┆ ---       ┆   ┆ ector      ┆ ustry_Gro ┆ nt        ┆ idates    │
│ str       ┆ str        ┆ f64    ┆ str       ┆   ┆ ---        ┆ up        ┆ ---       ┆ ---       │
│           ┆            ┆        ┆           ┆   ┆ str        ┆ ---       ┆ f64       ┆ u32       │
│           ┆            ┆        ┆           ┆   ┆            ┆ str       ┆           ┆           │
╞═══════════╪════════════╪════════╪═══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ C00064774 ┆ LOEBSACK   ┆ 1000.0 ┆ H6IA02146 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 530250.0  ┆ 152       │
│           ┆ FOR        ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆ CONGRESS   ┆        ┆           ┆   ┆ ties']     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆            ┆ n, T…     ┆           ┆           │
│ C00064774 ┆ MCNERNEY   ┆ 1000.0 ┆ H4CA11081 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 530250.0  ┆ 152       │
│           ┆ FOR        ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆ CONGRESS   ┆        ┆           ┆   ┆ ties']     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆            ┆ n, T…     ┆           ┆           │
│ C00064774 ┆ HASTINGS   ┆ 1500.0 ┆ H2FL23021 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 530250.0  ┆ 152       │
│           ┆ FOR        ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆ CONGRESS   ┆        ┆           ┆   ┆ ties']     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆            ┆ n, T…     ┆           ┆           │
│ C00064774 ┆ KEVIN      ┆ 1000.0 ┆ H6CA22125 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 530250.0  ┆ 152       │
│           ┆ MCCARTHY   ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆ FOR        ┆        ┆           ┆   ┆ ties']     ┆ Generatio ┆           ┆           │
│           ┆ CONGRESS   ┆        ┆           ┆   ┆            ┆ n, T…     ┆           ┆           │
│ C00064774 ┆ JEFF       ┆ 1000.0 ┆ H2FL01100 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 530250.0  ┆ 152       │
│           ┆ MILLER FOR ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆ CONGRESS   ┆        ┆           ┆   ┆ ties']     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆            ┆ n, T…     ┆           ┆           │
│ …         ┆ …          ┆ …      ┆ …         ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ C00194746 ┆ TOM REED   ┆ 5000.0 ┆ H0NY29054 ┆ … ┆ ['Insuranc ┆ ['Insuran ┆ 370950.0  ┆ 114       │
│           ┆ FOR        ┆        ┆           ┆   ┆ e Carriers ┆ ce Carrie ┆           ┆           │
│           ┆ CONGRESS   ┆        ┆           ┆   ┆ and Relat… ┆ rs']      ┆           ┆           │
│ C00407080 ┆ TOM REED   ┆ 2500.0 ┆ H0NY29054 ┆ … ┆ ['Ambulato ┆ ['Offices ┆ 15400.0   ┆ 5         │
│           ┆ FOR        ┆        ┆           ┆   ┆ ry Health  ┆ of Physic ┆           ┆           │
│           ┆ CONGRESS   ┆        ┆           ┆   ┆ Care       ┆ ians',    ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ Servi…     ┆ 'Hom…     ┆           ┆           │
│ C00435990 ┆ TOM REED   ┆ 2000.0 ┆ H0NY29054 ┆ … ┆ ['Construc ┆ ['Nonresi ┆ 49500.0   ┆ 24        │
│           ┆ FOR        ┆        ┆           ┆   ┆ tion of    ┆ dential   ┆           ┆           │
│           ┆ CONGRESS   ┆        ┆           ┆   ┆ Buildings' ┆ Building  ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ ]          ┆ Cons…     ┆           ┆           │
│ C00015933 ┆ GAIL HUFF  ┆ 1000.0 ┆ H2NH01288 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 369000.0  ┆ 76        │
│           ┆ BROWN FOR  ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆ CONGRESS   ┆        ┆           ┆   ┆ ties',     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ 'Ma…       ┆ n, T…     ┆           ┆           │
│ C00015933 ┆ GAIL HUFF  ┆ 1000.0 ┆ H2NH01288 ┆ … ┆ ['Utilitie ┆ ['Electri ┆ 369000.0  ┆ 76        │
│           ┆ BROWN FOR  ┆        ┆           ┆   ┆ s', 'Utili ┆ c Power   ┆           ┆           │
│           ┆ CONGRESS   ┆        ┆           ┆   ┆ ties',     ┆ Generatio ┆           ┆           │
│           ┆            ┆        ┆           ┆   ┆ 'Ma…       ┆ n, T…     ┆           ┆           │
└───────────┴────────────┴────────┴───────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [46]:
import polars as pl
DATA_PATH = "s:/campaignfinance/data/"
elections = pl.read_csv(f"{DATA_PATH}electionratings/IE/house_ratings.csv")
elections = elections[:, 1:]

In [47]:
elections = elections.with_columns([
    pl.col("date").str.to_datetime().alias("date"),
    pl.col("date").str.to_datetime().dt.year().alias("year")
])

In [49]:
elections = elections.filter(pl.col("date").dt.month() > 5)

In [50]:
df_elec2 = (
    elections
    .group_by(["state", "district", "year"])
    .agg([
        pl.col("incumbent_party").first(),
        pl.col("incumbent").first(),
        pl.col("open").first(),
        pl.col("special").first(),
        pl.col("rating").mean()
    ])
)

In [59]:
df_elec1.join(df_elec2, on=["state", "district", "year", "incumbent_party", "incumbent"], how="left").with_columns(
    (pl.col("rating") - pl.col("rating_right")).alias("rating_diff")
).sort("rating_diff")

shape: (3_486, 12)
┌───────┬──────────┬──────┬─────────────┬───┬────────────┬─────────────┬─────────────┬─────────────┐
│ state ┆ district ┆ year ┆ incumbent_p ┆ … ┆ open_right ┆ special_rig ┆ rating_righ ┆ rating_diff │
│ ---   ┆ ---      ┆ ---  ┆ arty        ┆   ┆ ---        ┆ ht          ┆ t           ┆ ---         │
│ str   ┆ i64      ┆ i32  ┆ ---         ┆   ┆ i64        ┆ ---         ┆ ---         ┆ f64         │
│       ┆          ┆      ┆ str         ┆   ┆            ┆ i64         ┆ f64         ┆             │
╞═══════╪══════════╪══════╪═════════════╪═══╪════════════╪═════════════╪═════════════╪═════════════╡
│ WA    ┆ 10       ┆ 2012 ┆ null        ┆ … ┆ null       ┆ null        ┆ null        ┆ null        │
│ CA    ┆ 21       ┆ 2012 ┆ null        ┆ … ┆ null       ┆ null        ┆ null        ┆ null        │
│ TX    ┆ 34       ┆ 2012 ┆ null        ┆ … ┆ null       ┆ null        ┆ null        ┆ null        │
│ NY    ┆ 28       ┆ 2012 ┆ Democrat    ┆ … ┆ null       ┆ null        ┆ null        ┆ null        │
│ NV    ┆ 4        ┆ 2012 ┆ null        ┆ … ┆ null       ┆ null        ┆ null        ┆ null        │
│ …     ┆ …        ┆ …    ┆ …           ┆ … ┆ …          ┆ …           ┆ …           ┆ …           │
│ FL    ┆ 6        ┆ 2022 ┆ Republican  ┆ … ┆ 0          ┆ 0           ┆ -4.0        ┆ 4.285714    │
│ FL    ┆ 21       ┆ 2022 ┆ Republican  ┆ … ┆ 0          ┆ 0           ┆ -4.0        ┆ 4.285714    │
│ FL    ┆ 17       ┆ 2022 ┆ Republican  ┆ … ┆ 0          ┆ 0           ┆ -4.0        ┆ 4.285714    │
│ FL    ┆ 18       ┆ 2022 ┆ Republican  ┆ … ┆ 0          ┆ 0           ┆ -4.0        ┆ 4.285714    │
│ FL    ┆ 19       ┆ 2022 ┆ Republican  ┆ … ┆ 0          ┆ 0           ┆ -4.0        ┆ 4.285714    │
└───────┴──────────┴──────┴─────────────┴───┴────────────┴─────────────┴─────────────┴─────────────┘

In [52]:
df_elec2

shape: (3_480, 8)
┌───────┬──────────┬──────┬─────────────────┬─────────────┬──────┬─────────┬────────┐
│ state ┆ district ┆ year ┆ incumbent_party ┆ incumbent   ┆ open ┆ special ┆ rating │
│ ---   ┆ ---      ┆ ---  ┆ ---             ┆ ---         ┆ ---  ┆ ---     ┆ ---    │
│ str   ┆ i64      ┆ i32  ┆ str             ┆ str         ┆ i64  ┆ i64     ┆ f64    │
╞═══════╪══════════╪══════╪═════════════════╪═════════════╪══════╪═════════╪════════╡
│ CT    ┆ 1        ┆ 2024 ┆ Democrat        ┆ Larson      ┆ 0    ┆ 0       ┆ 4.0    │
│ NJ    ┆ 4        ┆ 2012 ┆ Republican      ┆ Smith       ┆ 0    ┆ 0       ┆ -4.0   │
│ PA    ┆ 10       ┆ 2012 ┆ Republican      ┆ Marino      ┆ 0    ┆ 0       ┆ -4.0   │
│ MO    ┆ 9        ┆ 2010 ┆ Republican      ┆ Luetkemeyer ┆ 0    ┆ 0       ┆ -4.0   │
│ TX    ┆ 26       ┆ 2014 ┆ Republican      ┆ Burgess     ┆ 0    ┆ 0       ┆ -4.0   │
│ …     ┆ …        ┆ …    ┆ …               ┆ …           ┆ …    ┆ …       ┆ …      │
│ IL    ┆ 6        ┆ 2014 ┆ Republican      ┆ Roskam      ┆ 0    ┆ 0       ┆ -4.0   │
│ MA    ┆ 4        ┆ 2018 ┆ Democrat        ┆ Kenendy III ┆ 0    ┆ 0       ┆ 4.0    │
│ NJ    ┆ 1        ┆ 2016 ┆ Democrat        ┆ Norcross    ┆ 0    ┆ 0       ┆ 4.0    │
│ CA    ┆ 41       ┆ 2024 ┆ Republican      ┆ Calvert     ┆ 0    ┆ 0       ┆ -1.0   │
│ MS    ┆ 4        ┆ 2024 ┆ Republican      ┆ Ezell       ┆ 0    ┆ 0       ┆ -4.0   │
└───────┴──────────┴──────┴─────────────────┴─────────────┴──────┴─────────┴────────┘

In [42]:
df_elec.sort("rating_diff", descending=True).head(10)

shape: (10, 11)
┌───────┬──────────┬──────┬───────────────┬───┬────────────┬────────────┬────────────┬─────────────┐
│ state ┆ district ┆ year ┆ incumbent_par ┆ … ┆ avg_rating ┆ max_rating ┆ min_rating ┆ rating_diff │
│ ---   ┆ ---      ┆ ---  ┆ ty            ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---         │
│ str   ┆ i64      ┆ i32  ┆ ---           ┆   ┆ f64        ┆ i64        ┆ i64        ┆ i64         │
│       ┆          ┆      ┆ str           ┆   ┆            ┆            ┆            ┆             │
╞═══════╪══════════╪══════╪═══════════════╪═══╪════════════╪════════════╪════════════╪═════════════╡
│ NJ    ┆ 7        ┆ 2012 ┆ Republican    ┆ … ┆ 0.210526   ┆ 4          ┆ -4         ┆ 8           │
│ NJ    ┆ 2        ┆ 2012 ┆ Republican    ┆ … ┆ 1.473684   ┆ 4          ┆ -4         ┆ 8           │
│ CA    ┆ 31       ┆ 2012 ┆ Republican    ┆ … ┆ -3.684211  ┆ 2          ┆ -4         ┆ 6           │
│ WI    ┆ 8        ┆ 2010 ┆ Democrat      ┆ … ┆ -0.454545  ┆ 3          ┆ -2         ┆ 5           │
│ IL    ┆ 17       ┆ 2010 ┆ Democrat      ┆ … ┆ 0.727273   ┆ 4          ┆ -1         ┆ 5           │
│ VA    ┆ 5        ┆ 2020 ┆ Republican    ┆ … ┆ -2.555556  ┆ 0          ┆ -4         ┆ 4           │
│ NE    ┆ 2        ┆ 2014 ┆ Republican    ┆ … ┆ -0.727273  ┆ 1          ┆ -3         ┆ 4           │
│ FL    ┆ 26       ┆ 2012 ┆ Republican    ┆ … ┆ -0.736842  ┆ 2          ┆ -2         ┆ 4           │
│ PA    ┆ 8        ┆ 2010 ┆ Democrat      ┆ … ┆ 1.363636   ┆ 3          ┆ -1         ┆ 4           │
│ CO    ┆ 3        ┆ 2010 ┆ Democrat      ┆ … ┆ 1.0        ┆ 3          ┆ -1         ┆ 4           │
└───────┴──────────┴──────┴───────────────┴───┴────────────┴────────────┴────────────┴─────────────┘

In [45]:
elections.filter((pl.col("year") == 2010) & (pl.col("state") == "WI") & (pl.col("district") == 8))

shape: (11, 10)
┌────────────────┬───────┬──────────┬────────────────┬───┬─────────┬────────┬───────────────┬──────┐
│ date           ┆ state ┆ district ┆ incumbent_part ┆ … ┆ special ┆ rating ┆ label         ┆ year │
│ ---            ┆ ---   ┆ ---      ┆ y              ┆   ┆ ---     ┆ ---    ┆ ---           ┆ ---  │
│ datetime[μs]   ┆ str   ┆ i64      ┆ ---            ┆   ┆ i64     ┆ i64    ┆ str           ┆ i32  │
│                ┆       ┆          ┆ str            ┆   ┆         ┆        ┆               ┆      │
╞════════════════╪═══════╪══════════╪════════════════╪═══╪═════════╪════════╪═══════════════╪══════╡
│ 2010-11-01     ┆ WI    ┆ 8        ┆ Democrat       ┆ … ┆ 0       ┆ -2     ┆ Lean          ┆ 2010 │
│ 00:00:00       ┆       ┆          ┆                ┆   ┆         ┆        ┆ Republican    ┆      │
│ 2010-10-28     ┆ WI    ┆ 8        ┆ Democrat       ┆ … ┆ 0       ┆ -2     ┆ Lean          ┆ 2010 │
│ 00:00:00       ┆       ┆          ┆                ┆   ┆         ┆        ┆ Republican    ┆      │
│ 2010-10-22     ┆ WI    ┆ 8        ┆ Democrat       ┆ … ┆ 0       ┆ -1     ┆ Tilt          ┆ 2010 │
│ 00:00:00       ┆       ┆          ┆                ┆   ┆         ┆        ┆ Republican    ┆      │
│ 2010-10-15     ┆ WI    ┆ 8        ┆ Democrat       ┆ … ┆ 0       ┆ -1     ┆ Tilt          ┆ 2010 │
│ 00:00:00       ┆       ┆          ┆                ┆   ┆         ┆        ┆ Republican    ┆      │
│ 2010-10-08     ┆ WI    ┆ 8        ┆ Democrat       ┆ … ┆ 0       ┆ -1     ┆ Tilt          ┆ 2010 │
│ 00:00:00       ┆       ┆          ┆                ┆   ┆         ┆        ┆ Republican    ┆      │
│ …              ┆ …     ┆ …        ┆ …              ┆ … ┆ …       ┆ …      ┆ …             ┆ …    │
│ 2010-10-01     ┆ WI    ┆ 8        ┆ Democrat       ┆ … ┆ 0       ┆ -1     ┆ Tilt          ┆ 2010 │
│ 00:00:00       ┆       ┆          ┆                ┆   ┆         ┆        ┆ Republican    ┆      │
│ 2010-09-24     ┆ WI    ┆ 8        ┆ Democrat       ┆ … ┆ 0       ┆ -1     ┆ Tilt          ┆ 2010 │
│ 00:00:00       ┆       ┆          ┆                ┆   ┆         ┆        ┆ Republican    ┆      │
│ 2010-09-17     ┆ WI    ┆ 8        ┆ Democrat       ┆ … ┆ 0       ┆ 1      ┆ Tilt Democrat ┆ 2010 │
│ 00:00:00       ┆       ┆          ┆                ┆   ┆         ┆        ┆               ┆      │
│ 2010-09-06     ┆ WI    ┆ 8        ┆ Democrat       ┆ … ┆ 0       ┆ 1      ┆ Tilt Democrat ┆ 2010 │
│ 00:00:00       ┆       ┆          ┆                ┆   ┆         ┆        ┆               ┆      │
│ 2010-08-23     ┆ WI    ┆ 8        ┆ Democrat       ┆ … ┆ 0       ┆ 3      ┆ Likely        ┆ 2010 │
│ 00:00:00       ┆       ┆          ┆                ┆   ┆         ┆        ┆ Democrat      ┆      │
└────────────────┴───────┴──────────┴────────────────┴───┴─────────┴────────┴───────────────┴──────┘

In [ ]:
elections = elections.with_columns([
    pl.col("date").str.to_datetime().alias("date"),
    pl.col("date").str.to_datetime().dt.year().alias("year")
])

# Aggregate ratings by taking the mean, and interpreting this as continuous values from -4 to 4
elections = (
    elections
    .group_by(["state", "district", "year"])
    .agg([
        pl.col("incumbent_party").first(),
        pl.col("incumbent").first(),
        pl.col("open").first(),
        pl.col("special").first(),
        pl.col("rating").mean()
    ])
)

elections = elections.with_columns([
    ((pl.col("incumbent_party") == "republican") & (pl.col("rating") < 0))
    .cast(pl.Int8)
    .alias("flip"),
    pl.col("rating").abs().alias("uncertainty")
]).rename({"year":"cycle"})